# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 467e390297398f7018de2c6789ab2f5b2c467d2afa5cab050ff1d067ba4c90bb462bf97e9eea313ae3ded0cf203f6c0b5932ba7a62bb0e59a66eb80c26089a35

test:
  secret_key_base: 6966c3cbc198f463214152447bf2fa157433b01aa63a8fc9748cb5ffd35f5e98b1084dbc4428758330ada74fc9c18bffdbfd43e36775bc76e27b646ca5eecb2b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
